server:
  port: 9027

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pass123
    url: jdbc:mysql://localhost:3306/PetexProjectDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mvc:
    dispatch-options-request: true

    
  mail:
    host: smtp.gmail.com
    port: 587
    username: mdsarfrazahmad852131@gmail.com
    password: mhvlotpkbaivgxnp
    properties:
      mail:
        smtp:
          starttls:
            enable: true  